chainflip-io/chainflip-sdk-monorepo

package.json, packages/sdk/src/swap/services/ApiService.ts, packages/sdk/src/swap/services/__tests__/ApiService.test.ts, packages/sdk/src/swap/types.ts, packages/swap/package.json, packages/swap/prisma/migrations/20230706120934_add_tx_hash_to_swap/migration.sql, packages/swap/prisma/schema.prisma, packages/swap/src/__tests__/processBlocks.test.ts, packages/swap/src/event-handlers/__tests__/__snapshots__/swapEgressScheduled.test.ts.snap, packages/swap/src/event-handlers/__tests__/__snapshots__/swapExecuted.test.ts.snap, packages/swap/src/event-handlers/__tests__/__snapshots__/swapScheduled.test.ts.snap, packages/swap/src/event-handlers/swapScheduled.ts, packages/swap/src/routes/__tests__/swap.test.ts, packages/swap/src/routes/swap/index.ts, packages/swap/src/utils/ServiceError.ts, pnpm-lock.yaml
need to publish the SDK + update the swapping app
=> feat(swap): lookup swap by tx hash [WEB-240]

packages/sdk/src/swap/sdk.ts, packages/sdk/src/swap/services/ApiService.ts, packages/sdk/src/swap/types.ts, packages/shared/src/__tests__/schema.test.ts, packages/shared/src/guards.ts, packages/shared/src/parsers.ts, packages/shared/src/schemas.ts, packages/swap/src/routes/__tests__/swap.test.ts, packages/swap/src/routes/swap/index.ts, packages/swap/src/utils/__tests__/broker.test.ts, packages/swap/src/utils/broker.ts, packages/swap/src/utils/string.ts
=> feat(sdk, swap): add ccm metadata params [WEB-271]

packages/cli/tsup.config.mjs
=> chore(cli): add require

packages/sdk/src/swap/__tests__/sdk.test.ts, packages/sdk/src/swap/sdk.ts, packages/sdk/src/swap/types.ts
[WEB-371]
- add depositChannelExpiryTime to the sdk
=> feat(sdk,swap): [WEB-371] add depositChannelExpiryTime to the sdk

packages/swap/src/event-handlers/index.ts, packages/swap/src/event-handlers/networkChainStateUpdated.ts
[WEB-371]
- add ChainTracking to events
=> fix(swap): [WEB-371] add ChainTracking to events

packages/swap/src/event-handlers/networkChainStateUpdated.ts
[WEB-371]
- chain state updated args should accept number too
=> fix(swap): [WEB-371] chain state updated args should accept number too

packages/swap/src/event-handlers/swapDepositAddressReady.ts, packages/swap/src/handlers/__tests__/openSwapDepositChannel.test.ts, packages/swap/src/handlers/openSwapDepositChannel.ts
[WEB-371]
- save srcChainExpiryBlock on opening deposit channel
=> fix(swap): [WEB-371] save srcChainExpiryBlock on opening deposit channel

packages/swap/src/event-handlers/__tests__/__snapshots__/swapDepositAddressReady.test.ts.snap, packages/swap/src/event-handlers/__tests__/swapDepositAddressReady.test.ts, packages/swap/src/event-handlers/__tests__/utils.ts, packages/swap/src/event-handlers/swapDepositAddressReady.ts
[WEB-371]
- deposit amount is overwritten with zero in swapDepositAddressReady
=> fix(swap): [WEB-371] deposit amount is overwritten with 0 in swapDepositAddressReady

packages/shared/src/validation/addressValidation.ts
I found this check in the FE validations
=> fix(swap): check address length

packages/sdk/src/swap/__tests__/sdk.test.ts, packages/sdk/src/swap/assets.ts, packages/sdk/src/swap/sdk.ts, packages/sdk/src/swap/services/__tests__/ApiService.test.ts, packages/shared/src/rpc/__tests__/index.test.ts, packages/shared/src/rpc/__tests__/utils.test.ts, packages/shared/src/rpc/index.ts, packages/shared/src/rpc/utils.ts, packages/shared/src/tests/fixtures.ts
Preparation for https://github.com/chainflip-io/chainflip-backend/pull/4419
=> chore(sdk): Make minimum_swap_amounts property of swapping environment optional

packages/swap/src/__tests__/integration.test.ts, packages/swap/src/routes/__tests__/quote.test.ts, packages/swap/src/routes/quote.ts
=> chore(sdk): update quote query response type

packages/shared/src/node-apis/__tests__/redis.test.ts, packages/shared/src/node-apis/redis.ts
=> feat: handle new ingress egress asset shape

packages/swap/src/__tests__/integration.test.ts, packages/swap/src/quoting/QuotingClient.ts, packages/swap/src/quoting/__tests__/quotes.test.ts, packages/swap/src/quoting/quotes.ts, packages/swap/src/quoting/schemas.ts, packages/swap/src/routes/quote.ts, packages/swap/src/utils/statechain.ts
=> feat(swap): add monitoring to quoting client

packages/sdk/src/swap/services/ApiService.ts, packages/sdk/src/swap/services/__tests__/ApiService.test.ts, packages/sdk/src/swap/services/__tests__/__snapshots__/ApiService.test.ts.snap, packages/sdk/src/swap/types.ts, packages/shared/src/__tests__/functions.test.ts, packages/shared/src/functions.ts, packages/shared/src/parsers.ts, packages/shared/src/schemas.ts, packages/swap/prisma/migrations/20240214130711_/migration.sql, packages/swap/prisma/schema.prisma, packages/swap/src/quoting/quotes.ts, packages/swap/src/routes/__tests__/quote.test.ts, packages/swap/src/routes/quote.ts, packages/swap/src/utils/fees.ts
just restoring some work i accidentaly nuked from the `feat/boost` branch
And fixing merge conflicts for the last 75 commits :S
=> feat: extend quote fetching logic to include fee

packages/shared/src/functions.ts, packages/swap/src/event-handlers/common.ts, packages/swap/src/routes/swap.ts
- add Arbitrum to getStatus endpoint
- support arb in deposit address ready event
=> fix(swap): add Arbitrum to status endpoint

.github/dependabot.yaml, jest.config.mjs, packages/cli/package.json, packages/cli/tsconfig.json, packages/sdk/package.json, packages/sdk/src/swap/sdk.ts, packages/sdk/tsconfig.json, packages/shared/package.json, packages/shared/src/__tests__/parsers.test.ts, packages/shared/src/broker.ts, packages/shared/src/node-apis/redis.ts, packages/shared/src/parsers.ts, packages/shared/src/validation/addressValidation.ts, packages/shared/src/vault/executeSwap.ts, packages/shared/tsconfig.cjs.json, packages/shared/tsconfig.json, packages/shared/tsconfig.mjs.json, packages/swap/package.json, packages/swap/src/event-handlers/__tests__/depositIgnored.test.ts, packages/swap/src/event-handlers/__tests__/depositIgnoredV120.test.ts, packages/swap/src/event-handlers/common.ts, packages/swap/src/event-handlers/depositIgnored.ts, packages/swap/src/event-handlers/depositIgnoredV120.ts, packages/swap/src/event-handlers/networkDepositReceived.ts, packages/swap/tsconfig.json, pnpm-lock.yaml
=> refactor: remove polkadot packages

packages/sdk/src/swap/types.ts, packages/swap/src/routes/__tests__/swap.test.ts, packages/swap/src/routes/swap.ts
=> chore(swap): add refund aborted state to sdk response

CHANGELOG.md, packages/swap/src/routes/__tests__/swap.test.ts, packages/swap/src/routes/swap.ts
Deposit channel info present here:
https://chainflip-swap-perseverance.chainflip.io/swaps/16702-Ethereum-15
but absent here:
https://chainflip-swap-perseverance.chainflip.io/swaps/10
=> fix(swap): always query deposit channel

packages/sdk/src/swap/assets.ts, packages/shared/src/enums.ts, packages/shared/src/vault/executeSwap.ts, packages/swap/src/event-handlers/__tests__/__snapshots__/ccmSwap.test.ts.snap, packages/swap/src/event-handlers/__tests__/__snapshots__/swapEgressScheduled.test.ts.snap, packages/swap/src/event-handlers/__tests__/swapEgressScheduled.test.ts, packages/swap/src/event-handlers/swapEgressScheduled.ts
The egress fees were stored using the wrong asset.
=> fix(swap): use gas asset for ccm egress fee [WEB-1424]

packages/sdk/src/swap/sdk.ts
i wrestled with the test on this one. but failed :(
closes WEB-1521
=> feat(sdk): referesh cf_environment cache every minute

CHANGELOG.md, packages/shared/src/consts.ts, packages/shared/src/schemas.ts, packages/swap/src/__tests__/__snapshots__/integration.test.ts.snap, packages/swap/src/routes/__tests__/__snapshots__/quote.test.ts.snap, packages/swap/src/routes/__tests__/v2/quote.test.ts, packages/swap/src/utils/getPoolQuote.ts
Linear: [Expose recommended slippage tolerance from getQuote](https://linear.app/chainflip/issue/WEB-1556/expose-recommended-slippage-tolerance-from-getquote)
=> fix(swap): expose recommended slippage tolerance from getQuote

packages/shared/src/vault/executeSwap.ts
- Add `cfParameters` versioning byte (enum)
- Simplify logic
=> chore: add versioning and simplify

packages/swap/src/ingress-egress-tracking/__tests__/index.test.ts, packages/swap/src/ingress-egress-tracking/index.ts, packages/swap/src/routes/__tests__/v2/swap.test.ts
Added  `transactionRef`field returned from `getPendingDeposit`
=> fix: added transaction ref to pending deposits[WEB-1643]

packages/shared/src/broker.ts, packages/shared/src/vault/executeSwap.ts
This would solve a problem we currently have in setting up bouncer for assethub.
=> This commit adds Assethub support to the the `encodeAddress` function.

CHANGELOG.md, packages/swap/src/routes/__tests__/v2/swap.test.ts, packages/swap/src/routes/v2/utils.ts, packages/swap/src/utils/swap.ts
=> chore(swap): test vault swap deposit failed is picked up by sdk

packages/swap/src/backfilling/backfillBeneficiaries.ts
The block might have more swap requests than channels we are trying to backfill. Therefore we need to iterate over every channel looking for the correct data rather than the other way around.
=> fix(swap): fix queue logic [WEB-1998]

packages/swap/src/server.ts, packages/swap/src/utils/logger.ts
```json
{"component":"SWAP","error":{},"info":{"amount":"1","destAsset":"Usdc","srcAsset":"Eth","usdValue":"9800"},"level":"error","message":"error while collecting quotes:","reqId":"ccf291f8-5439-4c88-aaeb-8964fd6c143d","timestamp":"25-02-25 13:23:31"}
```
=> refactor(swap): add request id to logs

packages/sdk/src/swap/v2/types.ts, tsconfig.json
We removed comments before :(
Now the JSDocs work:
=> chore(sdk): emit comments

packages/swap/src/event-handlers/index.ts, packages/swap/src/event-handlers/ingress-egress/boostPoolCreated.ts, packages/swap/src/event-handlers/lending-pools/__tests__/__snapshots__/boostPoolCreated.test.ts.snap, packages/swap/src/event-handlers/lending-pools/__tests__/boostPoolCreated.test.ts, packages/swap/src/event-handlers/lending-pools/boostPoolCreated.ts
=> chore(lp): migrate boost pool for 1.10

scripts/publishPackage.mts
This reverts commit d5f30564d6dc3392e27a709053e51a37aee4280b.
=> revert: chore: tag on publish (#1433)

packages/swap/src/event-handlers/swapping/__tests__/__snapshots__/swapRequested.test.ts.snap, packages/swap/src/event-handlers/swapping/__tests__/__snapshots__/swapRescheduled.test.ts.snap, packages/swap/src/event-handlers/swapping/__tests__/swapRequested.test.ts, packages/swap/src/event-handlers/swapping/__tests__/swapRescheduled.test.ts, packages/swap/src/event-handlers/swapping/swapDepositAddressReady.ts, packages/swap/src/event-handlers/swapping/swapExecuted.ts, packages/swap/src/event-handlers/swapping/swapRequested.ts, packages/swap/src/event-handlers/swapping/swapRescheduled.ts, packages/swap/src/routes/v2/__tests__/swap.test.ts, packages/swap/src/routes/v2/__tests__/swap/solanaFallback.test.ts
=> chore: cleanup 1.11
